### PR TITLE
The implementation of milestone 5

### PR DESCRIPTION
**Pull request by jingtaozf**

### CODE REVIEW

**Review by danielkrizian — COMMENTED** [review]
have you dev-tested this yourself? I am getting error after executing `C-u M-x q-eval-line`
`Symbol's value as variable is void: q-qcon-program`
there is a forgotten and undefined `q-qcon-program` variable.
Can we actually use it as `defcustom` to specify name of the function that calls the qcon? In the older versions of `q-mode` the name of the program used to be `qcon`, then it changed to `q-qcon` so it's good to parametrize it under `q-qcon-program`.

**Comment by danielkrizian** [comment]
can we make `nil` as default value for `helm-q-password-storage` ?

**Comment by jingtaozf** [comment]
> can we make `nil` as default value for `helm-q-password-storage` ?

Yes.

**Comment by jingtaozf** [comment]
> have you dev-tested this yourself? I am getting error after executing `C-u M-x q-eval-line`
> `Symbol's value as variable is void: q-qcon-program`
> there is a forgotten and undefined `q-qcon-program` variable.
> Can we actually use it as `defcustom` to specify name of the function that calls the qcon? In the older versions of `q-mode` the name of the program used to be `qcon`, then it changed to `q-qcon` so it's good to parametrize it under `q-qcon-program`.

It has already been a custom variable in q-mode.el and helm-q never change it.
https://github.com/psaris/q-mode/blob/master/q-mode.el#L186

This should be a bug of helm-q when it tries to expand file name of `q-qcon-program`, which works in my machine because I change `q-qcon-program` to a local full path file, I have fixed it in the latest commit.

**Comment by danielkrizian** [comment]
I am still getting `Symbol's value as variable is void: q-qcon-program`. Note that I am using older version of `q-mode` where probably `q-qcon-program` is not defined. So i had to circumvent that with kludge `(setq q-qcon-program "qcon")`

then I load the file with `M-x load-file`. Now when i again try `C-u M-x q-eval-line`, I get different error:
```
Symbol's value as variable is void: trim-string
```

**Comment by jingtaozf** [comment]
> I am still getting `Symbol's value as variable is void: q-qcon-program`. Note that I am using older version of `q-mode` where probably `q-qcon-program` is not defined. So i had to circumvent that with kludge `(setq q-qcon-program "qcon")`
> 
> then I load the file with `M-x load-file`. Now when i again try `C-u M-x q-eval-line`, I get different error:
> 
> ```
> Symbol's value as variable is void: trim-string
> ```

I used a function in my own =.emacs= file, it has been removed in the latest commit, please test it again.
I am sorry for it.

**Comment by danielkrizian** [comment]
many thanks, the displaying of `q-active-buffer` works now.
there is another issue:
when i do `C-u q-eval-line` and select `:5000 TAQ.HDB` which doesn't yet have qcon connection established, it does create the connection and the associated qcon buffer, but will not `q-send-string` to it. can you look into it please?
image

**Comment by jingtaozf** [comment]
> many thanks, the displaying of `q-active-buffer` works now.
> there is another issue:
> when i do `C-u q-eval-line` and select `:5000 TAQ.HDB` which doesn't yet have qcon connection established, it does create the connection and the associated qcon buffer, but will not `q-send-string` to it. can you look into it please?
> image

I can't' reproduce it.

**Pull request merged**
